Interfile 2 dicom converter
JPETTomography/j-pet-format-converter pull request #6
Opened 2020-12-01 10:51 UTC by In1th

2021-01-26 10:40 UTC, wkrzemien commented on interfile2DICOM.py
> +	main()
end of line missing

2021-01-26 10:55 UTC, wkrzemien commented on interfile2DICOM.py
> +	head_dict = readHeader('recon_3_1_it3.hdr')
Please, add argument to pass the interfile name.
Also, move this call (with recon_3_1_it3.hdr)  to tests

2021-03-15 11:43 UTC, wkrzemien commented on .gitignore
> +recon_3_1_it3.img
here is endOFile missing

2021-03-15 15:16 UTC, In1th commented on .gitignore
> +recon_3_1_it3.img
I couldn't find anything about end of file on .gitignore and I kinda don't understand what's wrong in here

2021-03-29 12:10 UTC, wkrzemien commented on .gitignore
> +recon_3_1_it3.img
Sorry, not end of file, but lack of end of line symbol. If you look above you can see the small red symbol. To get rid of it you just should '\n' symbol. See e.g.:
https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

2021-03-29 12:13 UTC, wkrzemien commented on interfile2DICOM.py
> +	main()
the same as above

2021-03-29 12:17 UTC, wkrzemien commented on interfile2DICOM.py
> +			arguments = parseHead(dictionary)
since you are using exceptions in the parseHead method, here you should have try except in the main function to catch the exceptions

2022-02-20 19:16 UTC, kamilrakoczy requested changes
I've added some initial comments.

It would also to be good to add some GHA CI to test that the tests are actually passing (example of the file configuring CI: https://github.com/JPETTomography/j-pet-framework/blob/master/.github/workflows/ci-workflow.yml#L1)

2022-02-20 19:16 UTC, kamilrakoczy commented on .gitignore
> +.*
Isn't this 2 rules ignoring like everything in root folder? I think they should be removed.

2022-02-20 19:16 UTC, kamilrakoczy commented on .gitignore
> +dicom.py
Probably should be removed.

2022-02-20 19:16 UTC, kamilrakoczy commented on .gitignore
> +examples/
Probably should be removed.

2022-02-20 19:16 UTC, kamilrakoczy commented on JPET_format_converter.egg-info/PKG-INFO
> +License: UNKNOWN
It looks like whole repository is under Apache license.

2022-02-20 19:16 UTC, kamilrakoczy commented on Makefile
> +MOD2 := writer
Looks like it is unused.

2022-02-20 19:16 UTC, kamilrakoczy commented on Makefile
> +	python3 $@
Looks unused.

2022-02-20 19:16 UTC, kamilrakoczy commented on Requirements.txt
> +numpy
There is convention, that this file should be named ``requirements.txt`` (lower case ``R``).

2022-02-20 19:16 UTC, kamilrakoczy commented on src/converter/converter.py
> +        pair_arr = zip(args.in_file,[None for i in args.in_file])
I think this can cause misleading behavior when length of the ``output_file`` is not equal ``in_file`` (user by accident enters less, or more output files). I'd say it would be better to only use default path, when there isn't any output files.

2022-02-20 19:16 UTC, kamilrakoczy commented on src/converter/settings.py
> +TEST_DIR = "/tmp/i2d_test"
Please use tempfile/tempdir instead of hardconding path/name: https://docs.python.org/3/library/tempfile.html

2022-02-20 19:16 UTC, kamilrakoczy commented on src/converter/writer.py
> +        entropy_srcs=[str(factory.random.randgen.getrandbits(100))] #? trochę nie wiem o co tutaj chodzi
Please remove the comment.

2022-02-20 19:16 UTC, kamilrakoczy commented on tests/reader_tests.py
> +        os.mkdir(TEST_DIR)
Same here, please use tempfile/tempdir

2022-02-20 19:16 UTC, kamilrakoczy commented on tests/writer_tests.py
> +        arg_dict = header_import(path= Path("/home/kruk/Code/Python/j-pet-format-converter/examples/recon_3_1_it3.hdr"))
Please don't use local path.

2022-02-20 19:16 UTC, kamilrakoczy commented on tests/writer_tests.py
> +        os.mkdir(TEST_DIR)
Please use tempfile/tempdir.

2022-02-20 20:23 UTC, In1th commented on .gitignore
> +.*
this ignores all hidden files and directories

2022-02-20 20:28 UTC, In1th commented on .gitignore
> +examples/
those are directories for module generation and i think it's not required in the repo

2022-05-11 07:21 UTC, wkrzemien commented
This is not the working version, but development is not ongoing, so I am merging it as it is to develop. Later somebody should finish it

2022-05-11 07:21 UTC, merged