Refactoring + data models
JPETTomography/j-pet-format-converter pull request #9
Opened 2022-07-13 08:50 UTC by Astrych

2022-07-14 09:01 UTC, graag requested changes
Struktura jest OK.

PyDantic zadba nam o to że w json są zdefiniowane wszystkie niezbędne pola.
Powinien też obsłużyć opcjonalne.

Kilka uwag do tego co już jest.

2022-07-14 11:30 UTC, Astrych commented on converter/converter.py
> +import converter.reader as rd
Pewnie, można, choć kiedyś miałem z tym jakiś problem (w innym projekcie) i po prostu zacząłem unikać. A jaki to był problem to nie pamiętam :) Ale mogę zmienić.

2022-07-14 11:31 UTC, Astrych commented on converter/writer.py
> +def write_from_interfile_header(obj: InterfileHeader, dataset: Dataset) -> Dataset:
Zostawiłem stare nazewnictwo, ale pewnie racja, write średnio pasuje.

2022-07-14 11:44 UTC, graag commented on tests/test_writer.py
> +        write_dicom(arg_dict, {})
Właśnie uświadomiłem sobie że i tak nie zadziała bo losujemy UID-y :)

2022-07-26 16:14 UTC, graag commented on converter/writer.py
> +    ds.is_little_endian = True
> is_little_endian[¶](https://pydicom.github.io/pydicom/dev/reference/generated/pydicom.dataset.Dataset.html#pydicom.dataset.Dataset.is_little_endian)
>
>  Shall be set before writing with write_like_original=False. The [Dataset](https://pydicom.github.io/pydicom/dev/reference/generated/pydicom.dataset.Dataset.html#pydicom.dataset.Dataset) (excluding the pixel data) will be written using the given endianness.

Wygląda że `ds.is_little_endian = True` ma wpływ na to jak zapisywane są dane. Z pixel data wydaje się że to my jesteśmy odpowiedzialni za zapewnienie odpowiedniego formatu bo jest trzymane jako bytes. Przy czytaniu do tego pixel_array wygląda że poprawnie konwertuje na odpowiedni format ...

2022-07-26 16:31 UTC, graag reviewed
Wygląda dobrze. Ciekawe jak sobie radzą te readery bez poprawnych danych w ImagePosition ...

2022-07-26 16:31 UTC, graag commented on converter/writer.py
> +            ds = create_slice_dataset(
Czy nie powinniśmy zapisywac jednak w dicom jakiejś informacji o slice?

2022-07-26 16:31 UTC, graag commented on converter/writer.py
> +            ds = create_slice_dataset(
Np ImagePosition w https://dicom.innolitics.com/ciods/ct-image/image-plane/00201041 ?? Obstawiam że Z powinno się różnić, nie?

Proponuję wczytać dwa kolejne obrazki DICOM CT z SIEMENS-a i porównac czym się różnią poza PixelData

2022-07-26 17:40 UTC, Astrych commented on converter/writer.py
> +            ds = create_slice_dataset(
Ach, właśnie, zapomniałem o tym całkiem. Być może to przez to nie działa xmedcon.

2022-07-28 11:42 UTC, graag approved these changes

2022-07-28 11:45 UTC, graag commented
@wkrzemien
Myślę że pierwsza wersja gotowa. Na razie dla modality CT.
To trafia do `develop` a potem jak dodamy modality PET razem może iść do `master`.

Przypisz proszę kogoś do review, chciałbym żeby to zostało zaakceptowane zanim pójdziemy dalej. Aurelien? Jakub?

2022-09-05 18:00 UTC, acoussat reviewed
Some general minor comments, mostly on coding style. I haven't tried the script in real life scenario, but I'd be pleased to do so if I am provided some test data!

2022-09-05 18:00 UTC, acoussat commented on converter/reader.py
> +    """
Probably a minor point, but two different docstring styles are mixed.

2022-09-05 18:00 UTC, acoussat commented on converter/reader.py
> +            # Get reast of the file
I think you meant "rest". :slightly_smiling_face:

2022-09-05 18:00 UTC, acoussat commented on converter/reader.py
> +                line = line.strip('!\n').split(':=')
To make the code clearer, I would use structural pattern marching here:
```python
key, value = line.strip('!\n').split(':=')
```
Especially given that it avoids redefining the `line` variable, which could make the code more confusing to read.

2022-09-05 18:00 UTC, acoussat commented on converter/writer.py
> +        creates a dicom file
That comment also appear one [line 156](https://github.com/JPETTomography/j-pet-format-converter/pull/9/files#diff-b303416c77f5061c86aad81a5957c99551b32eb5aec5c6b070ecd75e3d5a92c3R156).

2022-09-05 18:00 UTC, acoussat commented on main.py
> +                output_path += input_path.split('/')[-1].replace('.hdr','.dcm')
Just a matter of style, but to avoid redundancy I would write
```python
output_path += input_path.split('/')[-1].replace('.hdr', '.dcm' if extended_format else '')
```

2022-09-05 18:00 UTC, acoussat commented on main.py
> +        raise
Here, the current exception will be reraised, without being handled (https://stackoverflow.com/a/13957915). I think the whole `try..except` block can be removed.

2022-09-05 18:00 UTC, acoussat commented on tests/test_reader.py
> +        pass
Looks like the body of this test is missing, I don't know if it's intentional or not.

2022-09-22 09:14 UTC, graag commented
@acoussat I think all threads were addressed. Could you check?

For the next PR we'll have to come up with some safe artificial test images. And of course PET modality should be handled.

2022-09-23 07:08 UTC, acoussat commented
Everything looks good to me!

2022-09-27 12:58 UTC, wkrzemien approved these changes

2022-09-27 12:58 UTC, merged